title: minh trieu t., dl researcher
url: "https://mtrvn.github.io"
baseurl: "/trieutrg"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/mtrvn"
footer_text: "2025 by minh trieu t."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/trieutrg/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
